### ISSUE TITLE
Difficulty training

### ISSUE THREAD

**Issue by lgwplay** [piggy2009/DM_underwater#8]
Has anyone successfully trained it out? How effective is the training? I'm having trouble training and hope I can get help

**Comment by liuzhuobang9-ctrl** [comment]
> Has anyone successfully trained it out? How effective is the training? I'm having trouble training and hope I can get help有人训练成功了吗？培训效果如何？我在训练时遇到问题，希望能得到帮助
I trained successfully. What questions do you have?
